<div class="well">
<p>&copy; 2012 SLEPICE / ZF <br />
<small><?php echo $this->translate("Today is"); ?> <b><?php echo new Zend_Date($this->timestamp); ?></b> <?php if ($this->cachedTimestamp) { ?>(<?php echo $this->translate("Timestamp served from Memcached");?>)<?php } ?></small>

</div>
<ul class="nav nav-tabs">
    <li class="nav-header">
   	RSS
    </li>
    <?php 
	foreach($this->categories as $c){
	echo "<li><a href='/rss?category=$c->id'>$c->name</a> </li>".PHP_EOL;
	}
?>	
</ul>

</p>
