<div class="topbar">
  <div class="fill">
    <div class="container">
      <a class="brand" href="/">Project-F</a>
      <?php echo $this->navigation()->menu(); ?>
        <form action="<?=$this->baseUrl('/index/search')?>" class="pull-right">
            <input class="input" name="query" type="text" placeholder="">
            <button class="btn" type="submit"><?php echo $this->translate("Search"); ?></button>
        </form>
    </div>
  </div>
</div>

