<div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/">Project F</a>
          <?php if(Zend_Auth::getInstance()->hasIdentity() ) {?>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <?= $this->member['email']?>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/member/profile/index/id/<?= $this->member['id']?>">Public Profile</a></li>
              <li class="divider"></li>
              <li><a href="/member/index/logout">Sign Out</a></li>
            </ul>
          </div>
          <?php }?>
          
          <div class="nav-collapse">
            <ul class="nav">
       	  <?php 
					  $subtree = $this->navigation()->findOneByLabel('Home');
					   
					 $options = array("ulClass"=>"nav", 			
					  				"intent"=>"333",
					  				"minDepth" => 0,
					  				"maxDepth" => 0,
					 				"onlyActiveBranch" => false,
					 				"renderParents" => true);
					  
					  echo $this->navigation()->menu()->renderMenu(null,$options);

					  ?>
            </ul>
               <form class="form-search pull-right" method="GET" action="/browse-projects">
   				 <input type="text" name="q" type="text" class="input-medium search-query">
    			 <button type="submit" class="btn">Search in projects</button>
    			</form>
          </div><!--/.nav-collapse -->
           
        </div>
      </div>
    </div>

