<div class="hero-unit">
<h1>Hello!</h1>
<p>Welcome to the social platform for you and you.</p>
<p>
<a class="btn btn-primary btn-large" href="/index/learn-more">Learn more</a>
</p>
</div>

<ul class="thumbnails">
  <li class="span3">
    <div class="thumbnail">
      <img src="http://placehold.it/260x180" alt="">
      <h5>Thumbnail label</h5>
      <p>Thumbnail caption right here...</p>
    </div>
  </li>
    <li class="span3">
    <div class="thumbnail">
      <img src="http://placehold.it/260x180" alt="">
      <h5>Thumbnail label</h5>
      <p>Thumbnail caption right here...</p>
    </div>
  </li>

</ul>