
<link rel="stylesheet" href="<?=$this->baseUrl('/media/bootstrap/2.0.4.site/css/bootstrap.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/css/jquery.stepy.css')?>">
<script src="<?=$this->baseUrl('/js/libs/modernizr-2.0.6.min.js')?>"></script>
<script src="<?=$this->baseUrl('media/jquery/1.7.2/jquery.min.js')?>"></script>
<script src="<?=$this->baseUrl('media/bootstrap/2.0.4.site/js/bootstrap.min.js')?>"></script>   
<script src="<?=$this->baseUrl('/media/tools/flo-tools.js')?>"></script>


<!-- External libraries -->

<script src="<?=$this->baseUrl('/media/tools/jquery.validate.min.js')?>"></script>
<script src="<?=$this->baseUrl('/media/tools/jquery.form.js')?>"></script>
<script src="<?=$this->baseUrl('/media/tools/jquery.validate.bootstrap.js')?>"></script>