
<link rel="stylesheet" href="<?=$this->baseUrl('media/bootstrap/2.0.4/css/bootstrap.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/css/jquery.stepy.css')?>">

<script src="<?=$this->baseUrl('/js/libs/modernizr-2.0.6.min.js')?>">

<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
      <script>window.jQuery || document.write('<script src="<?=$this->baseUrl('media/jquery/1.7.2/jquery.min.js')?>"><\/script>')</script>
  
  <!-- Grab Google CDN's jBootstrap, with a protocol relative URL; fall back to local if offline -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.0.3/bootstrap.min.js"></script>
      <script>window.jQuery || document.write('<script src="<?=$this->baseUrl('media/bootstrap/2.0.4/js/bootstrap.min.js')?>"><\/script>')</script>
  <!-- end scripts-->


<script src="<?=$this->baseUrl('/media/tools/flo-tools.js')?>"></script>
