<?php
/**
 * @author   Kanstantsin A Kamkou (2ka.by)
 */


// Looks for any navigation pages requiring user information and injects it
$pages = $this->container->findAllBy('params_id', 'ID_USER');
foreach($pages as &$page){
	$page->setParams(array(
			'id'=> 1,
	));
}

$html = array('<ul class="nav nav-list">');
foreach ($this->container as $page) {

    // show only the current branch and the visible item
    if (!$page->isVisible() || ($this->menu()->getOnlyActiveBranch() && !$page->isActive(true))) {
        continue;
    }
    
    // header
    $html[] = '<li class="nav-header">';
    $html[] = '<a href="' . $page->getHref() . '">';
    $html[] = $page->getLabel();
    $html[] = "</a>";
    $html[] = "</li>";

    if (!empty($page->pages)) {
        foreach ($page->pages as $subpage) {
            // visibility of the sub-page
            if (!$subpage->isVisible()) {
                continue;
            }
            
            $html[] = '<li' . ($subpage->isActive() ? ' class="active"' : '') . '>';
            $html[] = '<a href="' . $subpage->getHref() . '">';

            if ($subpage->get('icon')) {
                $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
            }

            $html[] = $subpage->getLabel();
            $html[] = "</a>";
            $html[] = "</li>";

            // 2 depht menu
            if(!empty($subpage->pages)){
            	foreach($subpage->pages as $subsubpage){
            	$html[] = '<li' . ($subsubpage->isActive() ? ' class="active"' : '') . '>';
            	$html[] = '<a href="' . $subsubpage->getHref() . '">';
            	$html[] = "--".$subsubpage->getLabel();
            	$html[] = "</a>";
            	$html[] = "</li>";
            	
            	}
            }
        
        }
    }
}

$html[] = '</ul>';

echo join(PHP_EOL, $html);
?>