<!doctype html>
<head>
  <meta charset="utf-8">
  <title><?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>

<link rel="stylesheet" href="<?=$this->baseUrl('/media/data-tables-1.9.1/css/data-table-bootstrap2-additional.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/media/bootstrap/2.0.4.launch/css/bootstrap.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/media/slepice-launch/1.0.0/css/launchpage_css.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/css/jquery.stepy.css')?>">
<script src="<?=$this->baseUrl('/js/libs/modernizr-2.0.6.min.js')?>"></script>
<script src="<?=$this->baseUrl('media/jquery/1.7.2/jquery.min.js')?>"></script>
<script src="<?=$this->baseUrl('media/bootstrap/2.0.4.launch/js/bootstrap.min.js')?>"></script>   
<script src="<?=$this->baseUrl('/media/tools/flo-tools.js')?>"></script>

<script type='text/javascript'>
var __wtw_lucky_ref_id = 49974;
var __wtw_lucky_setup_key = {};
__wtw_lucky_setup_key.id = '4195';
__wtw_lucky_setup_key.key = 'dYrar7ekansaLvuepfZ3bLq8qbw936nW';

(function() {
var wa = document.createElement('script'); wa.type = 'text/javascript'; wa.async = true;
wa.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://ca195961') + '.luckyorange.com/w.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(wa, s);
 })();
</script>   

</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>




<a href="https://www.surveymonkey.com/s/flolaunchpage" class="btn btn-warning lp-btn-survey">
  S<br />U<br />R<br />V<br />E<br />Y
</a>

<div id="lp-container">
   
   <?= $this->action('header', 'index', 'launch');  ?> 
   

  <div id="lp-content">
    <div class="container">
      <div class="lp-flash-messenger"> 
      <?php echo $this->flashMessenger(); ?>
      </div>
      
      <div class="row">
        <?php echo $this->layout()->content; ?>
      </div>
    </div>
  </div>

  <?= $this->action('footer', 'index', 'launch');  ?> 

</div>


<!-- tracking services -->
<script type="text/javascript">
function woopraReady(tracker) {
    tracker.setDomain('floplatform.com');
    tracker.setIdleTimeout(432000000);
    tracker.trackPageview({type:'pageview',url:window.location.pathname+window.location.search,title:document.title});
    return false;
}
(function() {
    var wsc = document.createElement('script');
    wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
    wsc.type = 'text/javascript';
    wsc.async = true;
    var ssc = document.getElementsByTagName('script')[0];
    ssc.parentNode.insertBefore(wsc, ssc);
})();
</script>


</body>
</html>