<!doctype html>
<head>
  <meta charset="utf-8">
  <title><?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <link rel="stylesheet" href="<?=$this->baseUrl('/media/bootstrap/2.0.4/css/bootstrap.css')?>">
  <link rel="stylesheet" href="<?=$this->baseUrl('/media/data-tables-1.9.1/css/data-table-bootstrap2-additional.css')?>">
  <?= $this->action('lib', 'index', 'site');  // libraries ?>  
 </head>

<body>

    <div class="row-fluid">
      <div class="span10">
       <?= $this->action('header', 'index', 'launch');  ?>   
      	 <div class="well">
      	 <h1>FLO~ Start.Build.Lead.Grow.</h1>
   		  <img src="/css/launch/default/platform.png" alt="platform" id="platform" />
      	 </div> 
      	 <div class="well">
      	<?php echo $this->flashMessenger() ; // message generator; in style of bootstrap?>
   		<?php echo $this->layout()->content; ?>
        </div>
       <? //$this->action('footer', 'index', 'launch');  ?> 
      </div>

  </div> 


  

    
    
</body>
</html>