
  <a class="btn btn-xlarge btn-info" data-toggle="modal" href="#modal-form-application" >Apply for the first LEVEL position</a>
	    
	 <div class="modal hide" id="modal-form-application">
    		<div class="modal-header">
    		<button type="button" class="close" data-dismiss="modal">×</button>
    		<h3>Application</h3>
    		</div>
    		
    		<div class="modal-body">
		 	 		<?php echo $this->form;?>
		    </div>		   		
		    </div>
		   
	</div>



