Polls
<?php echo $this->form;?>


<div id='debug'></div>

<script type="text/javascript">
$(document).ready(function() { 
	var form = $('#form-application');
	var myModal = $('#modal-form-application');

	form.validate({
	    		rules: {
	    			answer_1 :{
		    			required: true,
	    				minlength: 2
			    		},
			    	answer_2 :{
		    			required: true,
	    				minlength: 2
			    		},
			    	answer_3 :{
			    			required: true,
		    				minlength: 2
				    		},
				    answer_4 :{
				    			required: true,
			    				minlength: 2
					    		},
					answer_5 :{
					    			required: true,
				    				minlength: 2
						    		},
	    			content: {
	    				required: true,
	    				minlength: 2
	    			}
	    		},
	    		   submitHandler: function(form) {
		    		   form.submit();
				 		myModal.modal('hide');					 		    
			 		   }
	    	}
	   );	
    }); 
</script>
