 <h3 class="fl-sidebar">Similar projects</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-similar-projects">
                  <ul class="fl-similar-projects-thumbnails">
                    <li>
                      <div class="fl-similar">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <h4>Web for Pub in Africa</h4>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>
                        </div>
                      </div>
                    </li>
                    
                    <li>
                      <div class="fl-similar">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <h4>Web for Pub in Africa</h4>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="fl-similar">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <h4>Web for Pub in Africa</h4>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="fl-similar">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <h4>Web for Pub in Africa</h4>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>