<?php
		// filtering tasks into 3 levels
		$tasks = array();
		if(count($this->tasks) > 0){
			foreach ( $this->tasks as $t ) {
				$tasks[$t->level][] = $t->toArray();
			}
		}
?>
<ul id="levelTab" class="nav nav-tabs">
	<li class="active"><a data-toggle="tab" href="#level1">Level 1</a></li>
	<li><a data-toggle="tab" href="#level2">Level 2</a></li>
	<li><a data-toggle="tab" href="#level3">Level 3</a></li>	
</ul>


<div id="levelTabContent" class="tab-content">
	<div id="level1" class="tab-pane fade in active">
	<?php 
		$level= 1;
		if(isset($tasks[$level])){ // if something for first level 
			echo '<ul>';
			foreach ( $tasks[$level] as $t ) {
					echo "<li>";
						$disabled = "disabled";
						if($t['finished']) $disabled = "disabled checked='checked'"; 
					echo "<input type='checkbox' $disabled >";
					echo  $t['task'] ." for level> ". $t['level'] ; 
					echo "</li>";
				}
			echo '</ul>';		
		}else {
			echo "No tasks for level ".$level;
		}
		?>
	</div>
	<div id="level2" class="tab-pane fade">
	<?php 
		$level = 2;
		if(isset($tasks[$level])){ // 
			echo '<ul>';
			foreach ( $tasks[$level] as $t ) {
					echo "<li>";
						$disabled = "disabled";
						if($t['finished']) $disabled = "disabled checked='checked'"; 
					echo "<input type='checkbox' $disabled >";
					echo  $t['task'] ." for level> ". $t['level'] ; 
					echo "</li>";
				}
			echo '</ul>';		
		}else {
				echo "No tasks for level ".$level;
		}
		?>
	</div>
	<div id="level3" class="tab-pane fade">
	<?php 
		$level = 3;
		if(isset($tasks[$level]) > 0){ // if something for first level 
			echo '<ul>';
			foreach ( $tasks[$level] as $t ) {
					echo "<li>";
						$disabled = "disabled";
						if($t['finished']) $disabled = "disabled checked='checked'"; 
					echo "<input type='checkbox' $disabled >";
					echo  $t['task'] ." for level> ". $t['level'] ; 
					echo "</li>";
				}
			echo '</ul>';		
		}else {
			echo "No tasks for level ". $level;
		}
		?>
	</div>
</div>	

<script>
// set the active level 
$('#levelTab li:eq(<?php echo ($this->project->level -1);?>) a').tab('show'); // Select third tab (0-indexed)
</script>

<hr>