<!doctype html>
<head>
  <meta charset="utf-8">
  <title>Project-F Beta / Admin / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>

  <link rel="stylesheet" href="<?=$this->baseUrl('/media/bootstrap/css/bootstrap.css')?>">
  <link rel="stylesheet" href="<?=$this->baseUrl('/media/data-tables-1.9.1/css/data-table-bootstrap2-additional.css')?>">
  
   <script src="<?=$this->baseUrl('media/tools/jquery-1.7.1.min.js')?>"></script>
	   <script src="<?=$this->baseUrl('js/libs/modernizr-2.0.6.min.js')?>"></script>
 	   
 </head>

<body>
 		<?= $this->action('header', 'index', 'site');  ?>
 			<?php 
		// if the user has identity
    	if(Zend_Auth::getInstance()->hasIdentity()){
    		echo $this->action('admin-menu', 'index', 'admin');  
    	}
    	 	
  		 ?>
  		 <?= $this->action('breadcrumbs', 'index', 'site');  ?>
  		 
  	<div class="row"> 
	       <div class="span3" >
	      	   <?= $this->action('left-menu', 'index', 'site');  ?>
	      </div>
	      <div class="span9">
	      	<!-- Bootstrap messaging generator -->
	      	<?php echo $this->flashMessenger() ; ?>
	        <?php echo $this->layout()->content; ?>
	      </div>
	       
	     
	      
    </div>
    
    <footer>
      <?= $this->action('footer', 'index', 'site');  ?>
    </footer>
    
    
  <!-- scripts concatenated and minified via ant build script-->
  <script defer src="<?=$this->baseUrl('media/bootstrap/js/bootstrap.js')?>"></script>
  <script defer src="<?=$this->baseUrl('js/plugins.js')?>"></script>
  <script defer src="<?=$this->baseUrl('js/script.js')?>"></script>
  <!-- end scripts-->

</body>
</html>