<h2><?php echo $this->project->title?> <?php echo $this->project->level;?></h2>
              <p class="fl_project_head_info"><i class="icon-user"></i> <a href="" title=""><?php echo $this->project->user->name?></a>, <i class="icon-folder-close"></i> caterogy, <i class="icon-time"></i> <?php echo $this->project->created->format('Y/m/d');?>, <i class="icon-thumbs-up"></i> <a href="" title="">like</a></p>

<?php
// basic project navigation
$this->step = 3;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

           </div>
       </div>

       <div class="row">
            <div class="span7">	
<h2>Comments</h2>
<p>Total number of comments <?php echo $this->paginator->getTotalItemCount();?> </p>
<?php echo $this->form;?>
<hr/>

<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    <?php if (count($this->paginator) > 0) {?>
    	<?php foreach ($this->paginator as $comment){ ?>

<div class="fl-cnt-100">
    		<div class="well">
		 		<img src="/storage/users/<?php echo $comment->user->getProfilePicture(100) ; ?>" />
				<?php echo $comment->user->name ; ?>
				<?php echo $comment->user->id ; ?>
				<?php echo $comment->created->format('d-m-y') ; ?>
				<?php echo $comment->content ; ?>
				<?php echo "pocet". count($comment->children) ; ?>
					
					<?php 
				// display children
				foreach($comment->children as $commentChild){
					?>		
				 <div class="alert alert-info">
				 	<img src="/storage/users/<?php echo $commentChild->user->getProfilePicture(100) ; ?>" />
   					<?php echo $commentChild->user->name ; ?>
					<?php echo $commentChild->user->id ; ?>
					<?php echo $commentChild->created->format('d-m-y') ; ?>
					<?php echo $commentChild->content ; ?>
					</div>
				<?php }?>
			</div>
		
    	
    	<?php } 
 	}
 	else {
	echo "No Comments for this project";
} ?>

</div>

</div>
