<h3><?php echo $this->project->title?></h3>
<?php
// basic project navigation
$this->step = 3;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>
<h2>Comments</h2>
<p>Total number of comments <?php echo $this->paginator->getTotalItemCount();?> </p>
<?php echo $this->form;?>
<hr/>

<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    <?php if (count($this->paginator) > 0) {?>
    	<?php foreach ($this->paginator as $comment){ ?>

    		<div class="well">
		 		<img src="/storage/users/<?php echo $comment->user->getProfilePicture(100) ; ?>" />
				<?php echo $comment->user->name ; ?>
				<?php echo $comment->user->id ; ?>
				<?php echo $comment->created->format('d-m-y') ; ?>
				<?php echo $comment->content ; ?>
				<?php echo "pocet". count($comment->children) ; ?>
					
					<?php 
				// display children
				foreach($comment->children as $commentChild){
					?>		
				 <div class="alert alert-info">
				 	<img src="/storage/users/<?php echo $commentChild->user->getProfilePicture(100) ; ?>" />
   					<?php echo $commentChild->user->name ; ?>
					<?php echo $commentChild->user->id ; ?>
					<?php echo $commentChild->created->format('d-m-y') ; ?>
					<?php echo $commentChild->content ; ?>
					</div>
				<?php }?>
			</div>
		
    	
    	<?php } 
 	}
 	else {
	echo "No Comments for this project";
} ?>
