 <?php if($this->project->ban){?>
    <div class="alert alert-danger">
    <strong>Warning!</strong> This project is banned.
    </div>				
<?php } ?>

 <?php  
	
	$allow[1] = false;
	$allow[2] = false;
	$allow[3] = false;
	$allow[4] = false;
	$allow[5] = false;
	$allow[6] = false;
	
	switch ($this->step){
		case 1 : $allow[1] = true;
		break;
		case 2 : $allow[2] = true;
		break;
		case 3 : $allow[3] = true;
		break;
		case 4 : $allow[4] = true;
		break;
		case 5 : $allow[5] = true;
		break;
		case 6 : $allow[6] = true;
		break;
	}	
  ?>
<div class="navbar fl-project-profile-navbar">
                <div class="navbar-inner">
                  <div class="container">
                      
                  

  <ul class="nav">
  <li class="<?php echo($allow[1] == true ? "active" : "disable" );?>"> <a href="/project/index/index/id/<?php echo $this->project->id?>">Summary</a></li>
  <li class="<?php echo($allow[2] == true ? "active" : "disable" );?>"><a href="/project/index/update/id/<?php echo $this->project->id?>">Updates</a></li>
  <li class="<?php echo($allow[3] == true ? "active" : "disable" );?>"><a href="/project/index/comment/id/<?php echo $this->project->id?>">Comments</a></li>
  <li class="<?php echo($allow[4] == true ? "active" : "disable" );?>"><a href="/project/index/survey/id/<?php echo $this->project->id?>">Project Survey</a></li>
  <li class="<?php echo($allow[5] == true ? "active" : "disable" );?>"><a href="/project/index/team/id/<?php echo $this->project->id?>">Team</a></li>
 <li class="<?php echo($allow[6] == true ? "active" : "disable" );?>"><a href="/project/index/project-board/id/<?php echo $this->project->id?>">Project Board</a></li>
 
  </ul>

  </div>
                </div>
              </div>