 <?php  
	
	$allow[1] = false;
	$allow[2] = false;
	$allow[3] = false;
	$allow[4] = false;
	$allow[5] = false;
	
	switch ($this->step){
		case 1 : $allow[1] = true;
		break;
		case 2 : $allow[2] = true;
		break;
		case 3 : $allow[3] = true;
		break;
		case 4 : $allow[4] = true;
		break;
		case 5 : $allow[5] = true;
		break;
	}
  ?>
  
  <ul class="nav nav-tabs">
  <li class="<?php echo($allow[1] == true ? "active" : "disable" );?>"> <a href="/project/index/index/id/<?php echo $this->project->id?>">main</a></li>
  <li class="<?php echo($allow[2] == true ? "active" : "disable" );?>"><a href="/project/index/update/id/<?php echo $this->project->id?>">updates</a></li>
  <li class="<?php echo($allow[3] == true ? "active" : "disable" );?>"><a href="/project/index/comment/id/<?php echo $this->project->id?>">comments</a></li>
  <li class="<?php echo($allow[3] == true ? "active" : "disable" );?>"><a href="/project/index/survey/id/<?php echo $this->project->id?>">survey</a></li>
  <li class="<?php echo($allow[3] == true ? "active" : "disable" );?>"><a href="/project/index/team/id/<?php echo $this->project->id?>">team</a></li>
  </ul>