<h2><?php echo $this->project->title?> <?php echo $this->project->level;?></h2>
              <p class="fl_project_head_info"><i class="icon-user"></i> <a href="" title=""><?php echo $this->project->user->name?></a>, <i class="icon-folder-close"></i> caterogy, <i class="icon-time"></i> <?php echo $this->project->created->format('Y/m/d');?>, <i class="icon-thumbs-up"></i> <a href="" title="">like</a></p>

<?php
// basic project navigation
$this->step = 5;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

           </div>
       </div>

       <div class="row">
            <div class="span7">	
<h2>Team</h2>
<div class="well">
<?php 	$creator = $this->project->user;
	 	$creatorRoles = $this->project->getCreatorRolesArray();
 		pr($creatorRoles);
?>


Creator: 
<?php echo $this->project->user->name;?>
</div>

<hr>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    <?php if (count($this->paginator) > 0) {?>
    	<?php foreach ($this->paginator as $answer){ ?>

    		<div class="well">
		 		<?php echo $answer->question->id;?>. <?php echo $answer->question->question;?>
		 		<hr>
		 		<?php echo $answer->answer;?>
		 		
			</div>
		
    	
    	<?php } 
 	}
 	else {
	echo "There is no team for this project";
} ?>

</div>
