<div class="span7">
	
<h2>Welcome back, <?php echo $this->member['name']?></h2>
<p>Your last visit was on <strong>20th of July 2012</strong></p>

              <div class="fl-cnt-100">
                <ul class="fl-dashboard">
                  <li><a href="" title=""><i class="fl-dashboard-icon-new"></i> Start new project</a></li>
                  <li><a href="" title=""><i class="fl-dashboard-icon-flobox"></i> FLO~ box</a></li>
                  <li><a href="" title=""><i class="fl-dashboard-icon-myprojects"></i> My projects</a></li>
                  <li><a href="" title=""><i class="fl-dashboard-icon-mycollaborations"></i> My collaborations</a></li>
                  <li><a href="" title=""><i class="fl-dashboard-icon-projectsilike"></i> Projects I like</a></li>
                  <li><a href="" title=""><i class="fl-dashboard-icon-peopleilike"></i> People I like</a></li>
                </ul>
              </div>

			<div class="fl-cnt-100">
			  <?php
				pr($this->member);
			  ?>
			</div>

              <div class="fl-cnt-100">
                <h3 class="fl-uppercase fl-top30">Recent projects <span>(people i like)</span></h2>
                <div class="fl_thick_divider"></div> 
                <ul class="fl-ul-list-style-none fl-thumb-projects4">
                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                          
                        </div>
                      </div>
                    </li>
                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                          
                        </div>
                      </div>
                    </li>
                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                          
                        </div>
                      </div>
                    </li>
                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                          
                        </div>
                      </div>
                    </li>
                </ul>
                
                <div class="btn-group fl-how-many">
                  <a class="btn" href="#">4</a>
                  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                  <ul class="dropdown-menu fl-dropdown-menu-numbers">
                      <li><a href="#">4</a></li>
                      <li><a href="#">8</a></li>
                      <li><a href="#">12</a></li>
                      <li><a href="#">16</a></li>
                  </ul>
                </div>
              </div>

              

              <div class="fl-cnt-100 fl-bottom20">
                <h3 class="fl-uppercase fl-top30">Featured projects</h2>
                <div class="fl_thick_divider"></div>  
                <ul class="fl-ul-list-style-none fl-member-projects">
                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                        </div>
                      </div>
                    </li>

                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level1 fl-similar-bar"></div>
                          </div>

                          <h4>Web for Pub in Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                        </div>
                      </div>
                    </li>
                </ul>
              </div>

</div>


