<h3>Welcome to your dashboard, <strong><?php echo $this->member['name']?></strong></h3>

<div class="well">
<ul class="nav">
  <li> <a class="btn " href="/member/flobox/index">FloBox</a></li>
  <li> <a class="btn " href="/member/my-project/">My Projects</a></li>
    <li> <a class="btn " href="/member/profile-setting/">My Settings</a></li>
</ul>

</div>


<div class="well">
<?php
pr($this->member);
?>
</div>


