<ul class="nav nav-pills">
		<li class="active"><a href="#">Private menu</a></li>
		<li class="dropdown" id="menu1"><a class="dropdown-toggle" data-toggle="dropdown" href="#menu1"> <?= $this->member['email']?> <b class="caret"></b>
		</a>
			<ul class="dropdown-menu">
				<li><a href="/member/dashboard/index">Dashboard</a></li>
				<li><a href="#">Another action</a></li>
				<li><a href="#">Something else here</a></li>
				<li class="divider"></li>
				<li><a href="#">Separated link</a></li>
			</ul></li>
	</ul>
