<div class="span10">
	<h2>About</h2>
	<p>
		Since the summer of 2011, we've been dreaming (fantasizing even) about creating a system to help people implement their ideas easier. So many people we know have such great vision and ingenuity, yet their plans and ambitions never get off of the ground. There are boatloads of reasons for why this could be. If you think about your own life, and your own circle of friends, we're sure you can relate to this. We've spent most of our waking time trying to address these fundamental questions. For the vast majority of people, the ideas are there, but a clear and actionable process of realizing them is simply not in place. So we tried to do the logical thing, and went to work on making the process clear and actionable. Here's what we came up with...
	</p>
	<p>
		FLO~ is a new way to think about entrepreneurship, collaboration and 'getting shit done'. We are a platform that promotes the genesis of ideas from initialization to realization and more than anything else, attempts to give you the opportunity to put your ideas into action. Why do so many great ideas get left on the drawing board, cocktail napkin or barroom floor? We believe that it's a problem of throughput, unsustainable motivation, and the uncertainty that arises from the absence of a clear-cut, actionable plan to work from. We've developed our system to try to attack this exact problem. Through productive collaboration, crowdsourced feedback, and frank self-evaluation, we hope to provide you with the tools to attack your ideas like never before. Let's create something beautiful together, and change the way we think about putting ideas into action.
	</p>
	<p>
		Further Reading:
		<ul>
			<li>Newsletter I: <a href="http://floplatform.com/newsletters/1.html" title="Newsletter I: What We Are">What We Are</a></li>
			<li>Newsletter II: <a href="http://floplatform.com/newsletters/2.html" title="Newsletter II: How We Work">How We Work</a></li>
			<li>The FLO~ <a href="http://floplatform.tumblr.com/post/23994542145/the-manifesto" title="The FLO~ Manifesto">Manifesto</a></li>
		</ul> 
	</p>

</div>
