<div class="span10">
	<h2>FAQ</h2>
	
<h3 class="lp-faq-question">Who is responsible for monitoring the quality of projects?</h3>
<p class="lp-faq">As administrators, we’ll do our best to sift through and only allow great project content to be posted on the FLO~ Platform. However, project creators are solely responsible for how they interact within FLO~.</p>

<h3 class="lp-faq-question">Who benefits from using FLO~?</h3>
<p class="lp-faq">FLO~ is focused on early-stage entrepreneurs of any variety. We're a great place for anyone with an idea or passion for a project. The topic or genre of the project itself is less important (in could be art, food, design, tech, etc.), what’s more important, is that our users are passionate in their desires to bring it to life.</p>

<h3 class="lp-faq-question">How does FLO~ make money? Do you plan on taking some percentage of ownership or intellectual property on projects?</h3>
<p class="lp-faq">Absolutely not. Project creators keep 100% ownership of their work. Post-beta, we plan on introducing a price-plan structure that adopts a freemium model (a free option with restricted usage along with less-restrictive options that come with a set fee). As we take in more feedback and begin meeting with our early test user, we will continue to keep you updated on fees and price plans that will be implemented in the future. We want to be as transparent as possible here.</p>

<h3 class="lp-faq-question">So is FLO~ free?</h3>
<p class="lp-faq">Yes, for now. As we progress, and as we build a stronger, more valuable product for our users we will begin to introduce price-plan options (of which there will always be a free option). You will always be kept updated and notified about these types of changes.</p>


<h3 class="lp-faq-question">Does FLO~  investigate what a project says it’s going to do?</h3>
<p class="lp-faq">FLO~ does not investigate a project’s claims. The claims and responsibilities of every project are its creator’s. The community ultimately decides the validity and worthiness of a project by whether they decide to collaborate or provide feedback for it.</p>

<h3 class="lp-faq-question">Are there any requirements for me to sign up for  FLO~ in beta?</h3>
<p class="lp-faq">We’ll be giving preference to two types of users: anyone located in Prague, and those who may be outside of Prague but who we already know personally. The reasons for this are that within beta testing, we will be looking to closely monitor and encourage quality projects and collaboration, while also organizing multiple offline meetups and feedback sessions. Early on, we believe it is to the benefit of the community for us to be able to interact both in person and online in order to build a like-minded trust.</p>


<h3 class="lp-faq-question">What makes this “beta testing”?</h3>
<p class="lp-faq">While we’ve worked hard to put together an application that we feel is useful, we still have one big step to complete: we need your validation. We want to know what features work, what doesn’t work, and what’s desperately missing. In order to accomplish this, we’re going to need a lot of your detailed user feedback, both online (in the form of surveys and emails) and offline (in the form of organized user meetups and in-person user-experience monitoring).</p>

<h3 class="lp-faq-question">I’ve signed up, when can I start using FLO~?</h3>
<p class="lp-faq">We’ll have our application ready for testing this summer. Don’t worry, we’ll definitely keep you updated on all of the details as the date gets nearer and clearer.</p> 


<h3 class="lp-faq-question">Do I have to protect my ideas and worry about people stealing them?</h3>
<p class="lp-faq">This will be covered in detail in our third newsletter. It’s a question we’ve been hearing a lot of late, and it’s one we feel very confident answering...it’s just that the answer is a bit involved.</p>

<h3 class="lp-faq-question">Who is FLO~?</h3>
<p class="lp-faq">FLO~ is Jerry Nunez, Jake Zahradnik, and a small team of extremely talented people.</p>

<h3 class="lp-faq-question">How can I contact FLO~?</h3>
<p class="lp-faq">You can contact us at either <a href="mailto:jake&#64;floplatform.com" title="">jake&#64;floplatform.com</a> or <a href="mailto:jerry&#64;floplatform.com" title="">jerry&#64;floplatform.com</a></p>

</div>
