<div class="container">
   <div class="lp-margin"></div>
   <div class="row">
     <div class="span4">
       
      <h4>Sign Up for our newsletter</h4>

      <form class="form" id="form-newsletter" method="post" action="index/newsletter">
        <fieldset>
          <div class="control-group">
            <label class="control-label hide" for="prependedInput">Input your email:</label>
            <div class="controls">
              <div class="input-prepend input-append">
                <span class="add-on"><i class="icon-envelope"></i></span><input class="span2" id="appendedPrependedInput" size="16" type="text" name="email"><input type="submit" class="btn" type="button" value="subscribe">
              </div>
              <p class="help-block">Hear about new features, tips and other updates.</p>
            </div>
          </div>
        </fieldset>
      </form>

     </div>

     <div class="span4 lp-text-align-right">
        
       <a href="http://www.facebook.com/floplatform" title="FLO~ on Facebook" onclick="window.open(this.href); return false;"><img src="/media/slepice-launch/1.0.0/img/icon_fb.png" alt="facebook" /></a>
       <a href="https://twitter.com/#!/flo_platform" title="FLO~ on Twitter" onclick="window.open(this.href); return false;"><img src="/media/slepice-launch/1.0.0/img/icon_twitter.png" alt="twitter" /></a>
       <a href="http://floplatform.tumblr.com/" title="FLO~ on Tumblr" onclick="window.open(this.href); return false;"><img src="/media/slepice-launch/1.0.0/img/icon_tumblr.png" alt="tumblr" /></a>
       <a href="http://vimeo.com/floplatform" title="FLO~ on Vimeo" onclick="window.open(this.href); return false;"><img src="/media/slepice-launch/1.0.0/img/icon_vimeo.png" alt="vimeo" /></a>
    
     </div>

      <div class="span2">
        
      <g:plusone size='small' count='true' href='http://www.floplatform.com'></g:plusone>
      <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.floplatform.com&amp;send=false&amp;layout=button_count&amp;width=160&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:160px; height:21px;" allowTransparency="true"></iframe>  
       
      </div>

   </div>

   <div class="lp-margin"></div>
   <div class="row lp-footer">
     <div class="span5">
        <p class="lp-copy">Copyright FLO, Inc. 2011. All rights reserved.</p>
     </div>
     <div class="span5">
        <p>Any questions or comments? We’re always checking these:</p> 
        <p class="lp-mails">
          <a href="mailto:jake&#64;floplatform.com" title="">jake&#64;floplatform.com</a>
          <a href="mailto:jerry&#64;floplatform.com" title="">jerry&#64;floplatform.com</a>
        </p>
     </div>
   </div>
</div>

 <!-- External libraries -->
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"></script>
<script type="text/javascript" src="http://malsup.github.com/jquery.form.js"></script>
<script src="<?=$this->baseUrl('/media/tools/jquery.validate.bootstrap.js')?>"></script>


 <!-- Google plus widget -->
    <script>
    (function(d, t) {
    var g = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = 'https://apis.google.com/js/plusone.js';
    s.parentNode.insertBefore(g, s);
    })(document, 'script');
    </script> 
     
<!-- Analytics -->    
    <script type="text/javascript" src="http://include.reinvigorate.net/re_.js"></script>
    <script type="text/javascript">
    try {
    reinvigorate.track("8903u-893969249n");
    } catch(err) {}
    </script>

    <!-- Carousel Slideshow Module -->
    <script type="text/javascript">
    //handle thumbnail click 
    $(document).ready(function() { 
      $('#carousel-nav a').click(function(q){
        q.preventDefault();
        targetSlide = $(this).attr('data-to')-1;
        $('#myCarousel').carousel(targetSlide);
        
        $('#descriptions div').each(function(o){
            $(this).css('display','none');
        });
        $('#description_'+targetSlide).css('display','block');
        
       });
    }); 
    </script> 

    <script type="text/javascript">
//wait for the DOM to be loaded 
$(document).ready(function() { 
  var form = $('#form-newsletter');

  form.validate({
          rules: {
            email :{
              required: true,
              email: true
              }
          },
           submitHandler: function(form) {
               form.submit();                 
        }
        }
     ); 
}); 
</script>