
<div class="span5">

<!-- Carousel Slideshow Module -->        
<div id="myCarousel" class="carousel lp-featured-size">
  <div class="carousel-inner">

      <ul class="thumbnails">
        
        <div class="item active" > 
        <li class="span5">
          <a data-toggle="modal" href="#myThumbnailModal1" class="thumbnail">
            <img src="/media/slepice-launch/1.0.0/img/featured_01.png" alt="">
          </a>
        </li>
        </div>

        <div class="item" >  
        <li class="span5">
          <a data-toggle="modal" href="#myThumbnailModal2" class="thumbnail">
            <img src="/media/slepice-launch/1.0.0/img/featured_02.png" alt="">
          </a>
        </li>
        </div>

        <div class="item" >  
        <li class="span5">
          <a data-toggle="modal" href="#myThumbnailModal3" class="thumbnail">
            <img src="/media/slepice-launch/1.0.0/img/featured_03.png" alt="">
          </a>
        </li>
        </div>

        <div class="item" >  
        <li class="span5">
          <a data-toggle="modal" href="#myThumbnailModal4" class="thumbnail">
            <img src="/media/slepice-launch/1.0.0/img/featured_04.png" alt="">
          </a>
        </li>
        </div>

        <div class="item" >  
        <li class="span5">
          <a data-toggle="modal" href="#myThumbnailModal5" class="thumbnail">
            <img src="/media/slepice-launch/1.0.0/img/featured_05.png" alt="">
          </a>
        </li>
        </div>

      </ul>

  </div>
</div>




       


        </div>
        <div class="span5">
         
         <p class="lp-editorial">It’s never been easier to begin a project and reach potential users or customers. It’s faster and cheaper than it’s ever been before. Unfortunately, that doesn't mean the process is any easier; it remains incredibly difficult. This is where FLO~ comes in...
  <strong>start</strong> a project by yourself, powered by your own inspiration and passion, <strong>build</strong> around a team of like-minded collaborators with a specific blend of skills, <strong>lead</strong> it through the development process, and <strong>grow</strong> your project into something successful and real.</p>  

<div id="descriptions">
  <div id="description_0" class="screen-description">
           <h3>Your Project</h3>
           <p>Showcase your great idea and allow potential investors and collaborators to have an immediate overview of the work you’ve done so far. Your project page will develop over time as your project itself does. The more time you spend here, the more likely you are to end up with something that people will actually use.</p>
  </div>

  <div id="description_1" style="display:none" class="screen-description">
           <h3>The Control Room</h3>
           <p>Start a new project, check on your existing ones, quickly navigate to liked users or projects you’re following, field collaboration requests, and much more. By keeping everything in one place, you’re never far from the controls, and it’s all accessible through the dashboard.</p>
  </div>

  <div id="description_2" style="display:none" class="screen-description">
           <h3>Take Action, and Work Through the Process</h3>
           <p>Guide your project through the levels of the FLO~ system. From ‘zero’ to ‘validated’, stay on the path to success with clearly defined goals every step of the way. Start at the beginning, collect feedback, collaborate with like-minded individuals, and turn your concept into a success while pivoting and adjusting the details along the way.</p>
  </div>

  <div id="description_3" style="display:none" class="screen-description">
           <h3>Brainstorm, and Plant the Seeds for Collaboration</h3>
           <p>Feel a surge of creativity? Get that idea down quickly and don’t let it slip away! Get as many eyes on it as possible, as much feedback as possible, and as soon as possible with the FLO~ Box. Follow other people’s creative process and begin collaborating on something new.</p>
  </div>

  <div id="description_4" style="display:none" class="screen-description">
           <h3>Collaborate and Build Your Team</h3>
           <p>Choose to work together with people from diverse backgrounds with different personality traits, putting the pieces together that are necessary to make your project whole. The people you choose to work with will be directly related to how far your idea will go, so pick them well.</p>
  </div>
</div>

<ul id="carousel-nav" class="lp-screens-navigation">
    <li class="lp-screens-navigation-thumbnails" id="carousel-nav-0" style="border: 2px solid #585999"><a href="#myCarousel" data-to="1" class="thumbnail"><img src="/media/slepice-launch/1.0.0/img/thumbnail_01.jpg" alt=""></a></li>
    <li class="lp-screens-navigation-thumbnails" id="carousel-nav-1"><a href="#myCarousel" data-to="2" class="thumbnail"><img src="/media/slepice-launch/1.0.0/img/thumbnail_02.jpg" alt=""></a></li>
    <li class="lp-screens-navigation-thumbnails" id="carousel-nav-2"><a href="#myCarousel" data-to="3" class="thumbnail"><img src="/media/slepice-launch/1.0.0/img/thumbnail_03.jpg" alt=""></a></li>    
    <li class="lp-screens-navigation-thumbnails" id="carousel-nav-3"><a href="#myCarousel" data-to="4" class="thumbnail"><img src="/media/slepice-launch/1.0.0/img/thumbnail_04.jpg" alt=""></a></li>
    <li class="lp-screens-navigation-thumbnails" id="carousel-nav-4"><a href="#myCarousel" data-to="5" class="thumbnail"><img src="/media/slepice-launch/1.0.0/img/thumbnail_05.jpg" alt=""></a></li>
</ul>

      </div>



<?php 
// settings, nastav si vsechno co chces rozbrazit za informace
$modalArr = array( 
 array("id" => "myThumbnailModal1","width-ratio"=> "1", "label"=>"Your Project","img" => "/media/slepice-launch/1.0.0/img/fullsize_01.jpg"),
 array("id" => "myThumbnailModal2","width-ratio"=> "1", "label"=>"The Control Room","img" => "/media/slepice-launch/1.0.0/img/fullsize_02.jpg"),
 array("id" => "myThumbnailModal3","width-ratio"=> "1", "label"=>"Take Action, and Work Through the Process","img" => "/media/slepice-launch/1.0.0/img/fullsize_03.jpg"),
 array("id" => "myThumbnailModal4","width-ratio"=> "1",  "label"=>"Brainstorm, and Plant the Seeds for Collaboration","img" => "/media/slepice-launch/1.0.0/img/fullsize_04.jpg"),
 array("id" => "myThumbnailModal5","width-ratio"=> "1", "label"=>"Collaborate and Build Your Team","img" => "/media/slepice-launch/1.0.0/img/fullsize_05.jpg")
);

foreach ($modalArr as $modal ) {
?>
<div class="modal hide" id="<?php echo $modal['id'];?>" style="display:none;padding:5px 5px 5px 5px;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><?php echo $modal['label'];?></h3>
  </div>
  <div class="modal-body">
    <img src="<?php echo $modal['img'];?>" alt="<?php echo $modal['label'];?>" title="<?php echo $modal['label'];?>" />
  </div>
  
</div>

<script type="text/javascript">
$('#<?php echo $modal['id'];?>').modal({
        backdrop: true,
        keyboard: true,
        show: false
    }).css({
       'width': function () { 
           return ($(document).width() * .9 * <?php echo $modal['width-ratio'];?> ) + 'px';  
           },
       'margin-left': function () { 
           return -($(this).width() / 2); 
       }
});
</script>


<?php
}
?>

