<div class="span10">
           


<h2>Privacy & Terms</h2>
<span class="h2span">Privacy Policy / Terms and Conditions: Floplatform.com</span>

<h3>A: TERMS AND CONDITIONS:</h3>

<h4>ACCEPTANCE</h4>

<p>
Floplatform.com (“FLO~”) provides this website and the related services (“Services”) to you subject to the following Terms of Service (“Terms”).  These Terms may be updated from time to time without notice to the end user.  These terms are freely amenable and changeable at any time at the choice or option of FLO~.  FLO~ has no duty to notify the end user of any changes.  It is the duty of the end user to check these Terms from time to time in order to ensure that they are in compliance with the most current changes.  All such guidelines are hereby incorporated by reference into these Terms.  By using this web site, you hereby agree to the following Terms.  You shall have no recourse for revocation of acceptance nor recourse for any damages resulting from the violation or breach of these Terms.
</p>

<h4>DESCRIPTION OF SERVICE</h4>

<p>
FLO~  provides users a platform test and build their ideas and projects, and  to connect with other users for the same purposes. At its current stage, however, the FLO~ application is untested ("BETA STAGE") and is therefore soliciting the feedback and usage of individuals ("BETA TESTERS") to further develop this technology.  For the purposes of this agreement, “Beta Stage” and “Beta Testers” shall be defined as follows:
</p>

<p class="definition">
A test of new or revised hardware or software that is performed by  users at their facilities under a varying array of operating conditions.  These  users (“Beta Testers”) shall not be considered employees nor independent contractors of FLO~.  
</p>

<p>
Unless specifically stated otherwise, any new features or plugins that augment the Services are subject to these Terms.  You understand that, by agreeing to these Terms, that these Services are being provided on an as-is basis.  This means that FLO~ assumes no responsibility for the following:
</p>

<ul>
  <li>Timeliness of Delivery</li>
  <li>Server Uptime</li>
  <li>Accuracy of Information</li>
  <li>Failure to Store Information</li>
  <li>Failure to Transmit Data</li>
</ul>

<p>
In no circumstances shall FLO~ be responsible from any damages, whether special or consequential, stemming from any of the aforementioned items.  The aforementioned disclaimers of liability are not the sole disclaimers sought by FLO~ and should not be construed as such.  Further disclaimers or liability shall be found later in this document.
</p>

<p>In order to use this service, you must have access to the World Wide Web and pay the fees associated with such connections.</p> 
<p>You must be 18 years old to access these Services.</p>
<p>All Terms in this agreement are subject to our privacy policy, below.</p>

<h4>PRIVACY POLICY</h4>
<p>
FLO~  is concerned about the privacy of our visitors. This policy statement tells you how we collect information from you and how we use it.  If you have any questions about the way we use our information, would like to make a suggestion, request a deletion or addition, please contact us directly at <a href="mailto:info&#64;floplatform.com" title="info&#64;floplatform.com">INFO@FLOPLATFORM.COM</a>
</p>
<p>
Certain areas of the web site may require registration or may otherwise ask you to provide personal information to participate in certain features or access certain content.  The decision to provide this information is purely optional; however, if you elect not to provide such information, you may not be able to access certain content or participate in certain features of the web site. When you provide information to the web site, you agree to provide only true, accurate, current and complete information on all registration pages.
</p>

<p>The personal information that we will be collecting is as follows: </p>

<ul>
  <li>A username or site alias (“Username”)</li>
  <li>E-mail address</li>
  <li>Physical address/location</li>
  <li>Website URL </li>
  <li>Password</li>
  <li>Application Name</li>
  <li>Application URL</li>
  <li>Application Description</li>
  <li>Application Screen Shot</li>
  <li>Logo</li>
</ul>

<p>
At our discretion, we may share this information with third parties for the purposes of marketing or improving the site.  This data will also be used to send any number of targeted mailings in order to best serve our user base.
</p>
<p>
This information will be collected and stored using a standard Secure Socket Layer Certificate.  This site is coded using HTML, PHP, MYSQL, JAVA and JQUERY.
</p>

<h4>CUSTOMER CONDUCT</h4>
<p>
By agreeing to these terms, you understand that all information, data, text, software, music, images, or other information (collectively, “Data”) remains the sole responsibility of the user.  Irrespective of the fact that this information may be posted publicly or privately on message boards or any interactive portions of this site, the Data will never be the responsibility of FLO~.  If such information violates US or International Law, FLO~ may be forced to release user information including IP addresses, names and contact information.
</p>
<p>
Furthermore, FLO~ does not guarantee the accuracy of any other content posted on this site (either by a user or by FLO~).  Because such information remains the control of the user, you recognize that you may be subject to harmful or offensive content.  Under no circumstances shall FLO~  be responsible or liable in any way for any content on this site or any content associated with the Services provided, the Beta Testing or Beta Testers.
</p>
<p>
Subject to the above terms, you may NOT use this service to:
</p>

<ul>
  <li>Upload, post or otherwise transmit any material that may be considered harmful or defamatory</li>
  <li>Harm minors</li>
  <li>Impersonate any entity, not limited to impersonating an employee or agent of FLO~</li>
  <li>Forge headers or otherwise manipulate the origin of any post</li>
  <li>Upload, post or otherwise publish any content that is in violation of any copyright material</li>
  <li>Send or publish any unsolicited advertising</li>
  <li>Send or publish any software viruses</li>
  <li>Disrupt or interfere with this Service</li>
  <li>Violate any law</li>
</ul>
<p>
You understand that FLO~ may or may not pre-screen content that will be publicly published.  It is therefore, not the duty of FLO~ to “scrub” content prior to posting.  It is the duty of the user to ensure that, before posting or submitting, they are not in violation of these Terms.  FLO~  does reserve the right to delete or not publish any content for any reason.  
</p>
<p>
You further agree that you must bear all the risks associated with posting any content on the World Wide Web, including risks associated with completeness, truth, and disclosure.  
</p>
<p>
You also understand that FLO~ may disclose any submitted content if required by law and/or at the discretion of FLO~.
</p>


<h4>INTERNATIONAL USE</h4>

<p>
Given that the internet is a global network, you hereby recognize that you will company not only with American laws, but also with international laws and customs, including but not limited to international tariffs and treaties, customs and taxes.
</p>

<h4>LINKS</h4>

<p>
This Service may provide, or third parties to this site may provide, links to outside web pages.  Because FLO~ has no control over these external websites, you agree that FLO~ is not responsible for the content, uptime or maintenance of these third-party websites.  Due to this, FLO~ may not be held liable for any content stemming from these third-party websites.
</p>

<h4>COPYRIGHT AND INTELLECTUAL PROPERTY ISUES</h4>
<p>
By agreeing to these Terms, you agree to grant FLO~ a world-wide, royalty-free license to use, modify, sell, destroy, and otherwise alter ANY content that you submit to this site. 
</p>
<p>
Further, FLO~ disclaims any warranty stemming from any intellectual property break found on this site.  
</p>
<p>
If you believe that your work has been copied in a way that constitutes copyright infringement, please contact FLO~ at <a href="mailto:info&#64;floplatform.com" title="info&#64;floplatform.com">INFO@FLOPLATFORM.COM</a>
</p>

<h4>INDEMNITY</h4>
<p>
YOU AGREE TO HOLD FLO~ HARMLESS FOR ANY POSSIBLE CLAIM ARAISING OUT OF THE USE OF THESE SERVICES, FROM THIRD-PARTY SERVICES, OR ANYTHING PERTAINING TO OR RELATING TO THE USE OF THIS WEBSITE.
</p>
<p>
EVEN IF FOUND LIABLE, THE POSSIBLE DAMAGES OWED BY FLO~ SHALL BE CAPPED AT us $5.00.
</p>


<h4>TERMINATION</h4>

<p>
You may terminate your complicance with this agreement at any time by discontinuing your use of the Service.  Irrespective of when you choose to terminate, our limitation of liability and your indemnity obligations will survive.
</p>

<h4>GOVERNING LAW</h4>
<p>
This agreement shall be construed in accordance with the laws of the State of Delaware.  Any disagreement regarding this agreement shall be adjudicated solely in courts located in the State of Delaware.
</p>


</div>