<div class="span6">
<?php echo $this->form; ?>
</div>
<div class="span4">
  <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
  	<fieldset>
  		<legend>Donate</legend>
  		<p class="lp-donate">Dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing</p>

    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="JKWSQSSKGV8TY">
    <input type="image" class="lp-paypal-img" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </fieldset>
  </form>
</div>


<!-- External libraries -->
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"></script>
<script src="<?=$this->baseUrl('/media/tools/jquery.validate.bootstrap.js')?>"></script>
<script type="text/javascript" src="http://malsup.github.com/jquery.form.js"></script>
<script type="text/javascript">

//wait for the DOM to be loaded 
$(document).ready(function() { 
	var form = $('#form-sign-up-beta');

	form.validate({
	    		rules: {
	    			name :{
		    			required: true,
	    				minlength: 2
			    		},
			    	password :{
		    			required: true,
	    				minlength: 5,
			    		},

			    	password_verification: {
						required: true,
						minlength: 5,
						equalTo: "#password"
					},

					email: {
						required: true,
						email: true
					},

					email_verification: {
						required: true,
						equalTo: "#email"
					},

			    	location :{
			    			required: true,
				    		},
				    accept :{
				    			required: true,
					    		}
					
	    		},
	   			submitHandler: function(form) {
			   		form.submit();	 		    

		   		}	
	    		 
	    	}
	   );	


    }); ; 



</script>


