<!doctype html>

<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Project-F Beta / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="<?=$this->baseUrl('/css/style.css')?>">
  <link rel="stylesheet" href="<?=$this->baseUrl('/media/bootstrap/css/bootstrap.css')?>">
	 <?= $this->action('lib', 'index', 'site');  // libraries ?>

</head>

<body>
  <div class="row-fluid" style="margin-left:10px">
  <div class="span11" >
   
   <?= $this->action('header', 'index', 'site');  ?>
  	 <hr>		 
	 <?= $this->action('menu-debug', 'menu', 'project');  ?>  
	 <?= $this->action('breadcrumbs', 'index', 'site');  ?>
	 <hr>
   
    <div class="row-fluid">    
      <div class="span10">
         <!-- Bootstrap messaging generator -->
      	<?php echo $this->flashMessenger() ; ?>
        <?php echo $this->layout()->content; ?>
      </div>
    </div> 
    <footer>
      <?= $this->action('footer', 'index', 'site');  ?>
    </footer>
  </div>
</div>
</body>
</html>