<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Project-F Beta / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->
  <!-- CSS: implied media=all -->  
  <!-- CSS concatenated and minified via ant build script-->
  <link rel="stylesheet" href="<?=$this->baseUrl('/css/style.css')?>">
  <link rel="stylesheet" href="<?=$this->baseUrl('/css/bootstrap.css')?>">
  <!-- end CSS-->
  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->
  <!-- All JavaScript at the bottom, except for Modernizr / Respond.
       Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
       For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
	   <script src="<?=$this->baseUrl('js/libs/modernizr-2.0.6.min.js')?>"></script>
	     <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
</head>

<body>
  <div class="row-fluid" style="margin-left:10px">
  <div class="span11" >
   
   <?= $this->action('header', 'index', 'site');  ?>
   <?= $this->action('breadcrumbs', 'index', 'site');  ?>
  
    <div class="row-fluid">
      <div class="span2" >
      	   <?= $this->action('left-menu', 'index', 'site');  ?>
      </div>

      <div class="span10">
         <!-- Bootstrap messaging generator -->
      	<?php echo $this->flashMessenger() ; ?>
        <?php echo $this->layout()->content; ?>
      </div>
    </div> 
    <footer>
      <?= $this->action('footer', 'index', 'site');  ?>
    </footer>
  </div>
</div>
      
    

    
  <!-- JavaScript at the bottom for fast page loading -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
      <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>
  <!-- scripts concatenated and minified via ant build script-->
  <script defer src="<?=$this->baseUrl('js/libs/bootstrap.js')?>"></script>
  <script defer src="<?=$this->baseUrl('js/plugins.js')?>"></script>
  <script defer src="<?=$this->baseUrl('js/script.js')?>"></script>

  <!-- end scripts-->



  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

</body>
</html>