<?php if (count($this->user) != 0) { ?>

<div class="row">
	<div class="span3">
		<h1> <?php echo $this->user->getName(); ?> </h1>
		<img src="/storage/users/<?php echo $this->user->getProfilePicture()?>"
			alt="<?= $this->member['name'];?>">
	</div>


	<div class="span5">
    <?= $this->user->email; ?>
    <?= $this->user->emailVisibility; ?>
    <?= $this->user->dateOfBirth->format('Y/m/d'); ?> 
    <?= $this->user->dateOfBirthVisibility; ?>
    <?= $this->user->description; ?>

  
    <?= $this->user->getUserInfo()->getIm(); ?>
    <?= $this->user->getUserInfo()->getSkype(); ?>
    <?= $this->user->getUserInfo()->getWebsite(); ?>
    <?= $this->user->getUserInfo()->getPhone(); ?>
   
   
   </div>

</div>


<?php };?>