
 <?php if (count($this->user) != 0) { ?>   
    
    <h1>Member / Public Page </h1>
    
    <ul class="thumbnails">
  <li class="span3">
    <div class="thumbnail">
      <img src="http://placehold.it/260x180" alt="">
      <h5>  <?= $this->user->name; ?></h5>
      
    </div>
	</ul>
    
    
    <div class="well">
    
  
    <?= $this->user->email; ?>
    <?= $this->user->emailVisibility; ?>
    <?= $this->user->dateOfBirth->format('Y/m/d'); ?> 
    <?= $this->user->dateOfBirthVisibility; ?>
    <?= $this->user->description; ?>

   <?php 
   	//pr($this->user->getUserInfo());
   
   ?>
    <?= $this->user->userInfo->im; ?>
    <?= $this->user->getUserInfo()->getSkype(); ?>
    <?= $this->user->getUserInfo()->getWebsite(); ?>
    <?= $this->user->getUserInfo()->getPhone(); ?>
    
    
    </div>
    
    <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>
<?php };?>