  <h2 class="fl-bottom20">My collaborations</h2>

<?php 
// The main project navigation
$this->step = 1;
echo $this->partial('my-collaboration/my-collaboration-navigation.phtml',array("step" => $this->step));
?>

<div class="fl-cnt-100 fl-top">

<?php 
if(count ($this->applications) > 0){	
	foreach($this->applications as $a){
	  $project = $a->project; // role is for collaborator
?>

                <div class="fl-list-project">
                  <div class="fl-cnt-20">
                    <div class="fl-project-thumb">
                      <div class="inner-5">
                        <a href="" title=""><img src="slepice/img/project_img_small.jpg" alt="" title="" /></a>
                        <div class="progress fl-similar-project-bar">
                          <div class="fl_level<?php echo $a->level;?> fl-similar-bar"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-60">
                    <div class="inner-list-project">
                      <div class="fl-cnt-100">
                        <h3 class="fl-list-project-h3"><?php echo $project->title?></h3>
                        <p class="fl-list-project-info"><i class="icon-folder-close"></i> <?php echo $project->category->name?>, <i class="icon-eye-open"></i> 87 Followers</p>
                      </div>
                      <div class="fl-cnt-100 fl-top40">
                        <div class="fl-list-project-roles-available">
                          <img src="slepice/img/role40x40_4.png" alt="" title="" />
                          <img src="slepice/img/role40x40_4.png" alt="" title="" />
                          <img src="slepice/img/role40x40_4.png" alt="" title="" />
                          <img src="slepice/img/role40x40_4.png" alt="" title="" />
                        </div>
                        <div class="fl-list-project-roles-my">
                          <img src="slepice/img/role40x40_4.png" alt="" title="" />
                          <?php echo $a->roleName?>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-20">
                    <ul class="nav nav-pills nav-stacked fl-collaborations-nav">
                      <li><a href="" title="">Updates</a></li>
                      <li><a href="/project/index/project-board/id/<?php echo $project->id?>" title="">Project board</a></li>
                      <li><a href="" title="">Team</a></li>
                      <li><a href="#surveyModal-id-<?php echo $a->id;?>" title="" data-toggle="modal">Project survey</a></li>
                      <li><a href="" title="">Comments</a></li>
                    </ul>
                  </div>
                </div>

                <div class="fl_thin_divider"></div>

<div class="fl-cnt-100">

			<?php echo $a->created->format('Y/m/d h:m:s')?><br />

			<?php echo $a->description;?><br />		
			
			<a class="btn btn-info" href="/project/index/index/id/<?php echo $project->id?>">Project Public Page</a>

			<!-- modal  -->
		    	<div class="modal hide" id="surveyModal-id-<?php echo $a->id;?>">
				<div class="modal-body">
    			<p><?php echo $a->content;?></p>
    			</div>
    				<div class="modal-footer"> <a href="#" class="btn" data-dismiss="modal">Close</a></div>
    			</div>
</div>

<?php 
  } // end foreach
}else{
 	echo "No applications";
 } ?>

  </div>
</div>



