<h3>My Collaborations</h3>
<hr/>
<?php 
if(count ($this->projects) > 0){ ?>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>id</th>
			<th>image</th>
			<th>name</th>
			<th>created</th>
			<th>modified</th>
			<th>tags</th>
			<th>category</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
<?php 	
	foreach($this->projects as $project){
		?>
		<tr>
			<td><?php echo $project->id?></td>
			<td><img src="/storage/projects/<?php echo $project->dir?>/<?php echo $project->getPicture("small");?>" /></td>
			<td><?php echo $project->title?></td>
			<td><?php echo $project->created->format('Y/m/d');?></td>
			<td><?php echo $project->modified->format('Y/m/d');?></td>
			<td><?php echo $project->getTagsString()?> , <?php pr($project->getCreatorRolesArray());?> </td>
		
			<td><?php echo $project->category->name?>		
			</td>
			<td>
				<a class="btn btn-info" href="/project/index/index/id/<?php echo $project->id?>">Project Public Page</a>
				<a class="btn btn-info" href="/project/index/survey/id/<?php echo $project->id?>">Survey</a>
				<a class="btn btn-info" href="/project/index/project-board/id/<?php echo $project->id?>">DashBoard</a>
			</td>
		</tr>
		<?php	
	} // end foreach
	?>
	</tbody>
	</table>	


<?php } else {
	
	echo "No projects";
	
}?>



