<h3>Member Administration</h3>


<?php 
if(count ($this->users) > 0){ ?>

<?php 
$message_unban = "Make Free";
$message_ban = "Ban this user";

?>

<div id="result">
</div>

<div class="container" style="margin-top: 20px;">			
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
	<thead>
		<tr>
			<th>id</th>
			<th>name</th>
			<th>email</th>
			<th>registered</th>
			<th>roles</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
<?php 	
	foreach($this->users as $user){
		?>
		<tr>
			<td><?php echo $user->id?></td>
			<td><?php echo $user->name?></td>
			<td><?php echo $user->email?></td>
			<td><?php echo $user->created->format('Y/m/d');?></td>
			<td><?php echo implode(",",$user->getRolesArray())?>		
			</td>
			<td>
			<a class="btn btn-info" href="/member/profile/index/id/<?php echo $user->id?>">Profile</a>
			<a class="btn btn-info" href="/admin/member/log/id/<?php echo $user->id?>">Log</a>
			~ 
			<?php if($user->ban){?>
				<button class="btn btn-success ban" id="submit_ban" value="<?php echo $user->id?>" ><?php echo $message_unban?></button>
			<?php }else{ ?>
				<button class="btn btn-danger ban" id="submit_ban" value="<?php echo $user->id?>" ><?php echo $message_ban?></button>
			<?php }?>
			</td>
		</tr>
		<?php	
	} // end foreach
	?>
	</tbody>
	</table>	
	</div>
	
	 <script defer="defer" src="<?=$this->baseUrl('media/data-tables-1.9.1/js/jquery.dataTables.js')?>"></script>
	<script defer="defer" type="text/javascript" charset="utf-8" language="javascript" src="<?=$this->baseUrl('media/data-tables-1.9.1/js/DT_bootstrap.js')?>"></script>
	
	<!-- ban button -->
	 <script defer="defer" type="text/javascript" >
	 $(function(){ // document ready
		 // disable cache
		 $.ajaxSetup ({cache: false });  
		 //  load() functions   
		  var loadUrl = "/admin/ajax/ban-user";  
		  
		    $(".ban").click(function(){  
				// send request for changing the user state
		    	var value = $(this).val();
		    	var button = $(this);
		    	
		    	var request = $.ajax({
		    	  url: loadUrl,
		    	  type: "GET",
		    	  data: {id : value},
		    	  dataType: "json"
		    	});

		    	request.done(function(msg) {
					// if is ban
					if(msg.ban){
						button.attr('class', 'btn btn-success ban');
						button.html('<?php echo $message_unban?>');
					}else {
						button.attr('class', 'btn btn-danger ban');
						button.html('<?php echo $message_ban?>');
					}
			    	
		    	   $("#result").html(msg.ban);

		    	});

		    	request.fail(function(jqXHR, textStatus) {
		    	  alert( "Request failed: " + textStatus );
		    	});
		  });  
	 });
	</script> 
<?php } else {
	
	echo "No users";
	
}?>


