
<?php 
if(count ($this->user) > 0){ ?>

<h3><?php echo $this->user->name; ?>'s log / <a class="btn btn-success" href="/member/profile/index/id/<?php echo $this->user->id?>"> Public Profile</a> </h3>

<hr />
<a class="btn btn-info " href="/admin/member">Back to all members</a>
<hr />
<?php 
if(count($this->logs) > 0){ ?>

<div class="container" style="margin-top: 20px;">	
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
	<thead>
		<tr>
			<th>created</th>
			<th>message</th>
			<th>type</th>
		</tr>
	</thead>
	<tbody>

<?php
	foreach($this->logs as $log){ ?>
	<tr>
		<td><?php echo $log->created->format('Y-m-d')?></td>
			<td><?php echo $log->message?>	</td>
			<td><?php echo $log->type?></td>
	</tr>	
	<?php 	
	} // end of foreach ?>
	</tbody>
	</table>	
	</div>
	
<?php 
} else{
	echo "No logs messages for this member.";
}
 
} else {
	
	echo "This user wasn't found.";
	
}?>

