<h1>Welcome to FLO~! We’re so excited to have you onboard with us!</h1> 
<p>
We hope to share our vision with you, and grow together into a brand new way of thinking about collaboration and getting ideas off the ground.
</p>
<p>
Jerry and I started this because we’re both very passionate about starting new projects and creating new things. 
We wanted to be part of new, interesting projects and developments within our communities, and we wanted to see
great ideas get beyond bar talk and idle dreaming. We couldn’t be happier If this helps you to achieve similar
goals within your own community and beyond. Hopefully a few months after using our platform, you will be able
to tell us that we’ve succeeded in our mission. However, FLO~ can only be as powerful as its community: our
effectiveness and value will grow as collaboration and quality contributors grow. This is an opportunity for 
you to ‘get on at the ground floor’ of a grassroots movement geared towards success, creative discovery, and 
financial independence. 
</p>
