  <?php
  $this->step = 3;
  echo $this->partial('profile-setting/profile-setting-navigation.phtml',array("step" => $this->step));
  ?>

<h3>So you have some skills? Which one?</h3>
 <hr />


 <div class="row">
  <div class="span7">
   <?php  echo $this->form;   ?>

  </div>
  <div class="span4"> 
		  <div class="alert alert-info">
		 <a class="close" data-dismiss="alert">×</a>
		  <h4 class="alert-heading">ROLE 1 Description</h4>
		  We gonna chung pellentesque nibh et turpizzle. Shut the shizzle up shit tortizzle. I saw beyonces tizzles and my pizzle went crizzle eleifend rhoncizzle nisi. In hac break yo neck, yall platea dictumst. Gangster things. Funky fresh tellus gangsta, pretium yippiyo, mattis izzle, pimpin' vitae, nunc. Gizzle suscipizzle. Integer semper check out this rizzle shiz.
		  <h4 class="alert-heading">ROLE 2 Description</h4>
		  We gonna chung pellentesque nibh et turpizzle. Shut the shizzle up shit tortizzle. I saw beyonces tizzles and my pizzle went crizzle eleifend rhoncizzle nisi. In hac break yo neck, yall platea dictumst. Gangster things. Funky fresh tellus gangsta, pretium yippiyo, mattis izzle, pimpin' vitae, nunc. Gizzle suscipizzle. Integer semper check out this rizzle shiz.
	  <h4 class="alert-heading">ROLE 3 Description</h4>
		  We gonna chung pellentesque nibh et turpizzle. Shut the shizzle up shit tortizzle. I saw beyonces tizzles and my pizzle went crizzle eleifend rhoncizzle nisi. In hac break yo neck, yall platea dictumst. Gangster things. Funky fresh tellus gangsta, pretium yippiyo, mattis izzle, pimpin' vitae, nunc. Gizzle suscipizzle. Integer semper check out this rizzle shiz.
	  <h4 class="alert-heading">ROLE 4 Description</h4>
		  We gonna chung pellentesque nibh et turpizzle. Shut the shizzle up shit tortizzle. I saw beyonces tizzles and my pizzle went crizzle eleifend rhoncizzle nisi. In hac break yo neck, yall platea dictumst. Gangster things. Funky fresh tellus gangsta, pretium yippiyo, mattis izzle, pimpin' vitae, nunc. Gizzle suscipizzle. Integer semper check out this rizzle shiz.
	  <h4 class="alert-heading">ROLE 5 Description</h4>
		  We gonna chung pellentesque nibh et turpizzle. Shut the shizzle up shit tortizzle. I saw beyonces tizzles and my pizzle went crizzle eleifend rhoncizzle nisi. In hac break yo neck, yall platea dictumst. Gangster things. Funky fresh tellus gangsta, pretium yippiyo, mattis izzle, pimpin' vitae, nunc. Gizzle suscipizzle. Integer semper check out this rizzle shiz.
		  </div>
  </div>
</div>
 
