<?php 
// The main project navigation
$this->step = 6;
echo $this->partial('my-project/my-project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>


<?php 
// The main project navigation
$this->sub_step = 1;
echo $this->partial('my-project-team/my-project-navigation.phtml',array("step" => $this->sub_step,"project" => $this->project));
?>

<h3>My Team</h3>

<div>My Position</div>

<div>My Project People</div>

<div class="well">
	<a class="btn btn-info" href="/member/project/create-project-step-one">Create New Project</a>
</div>
