<?php 
// The main project navigation
$this->step = 6;
echo $this->partial('my-project/my-project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

<?php 
// The main project navigation
$this->sub_step = 2;
echo $this->partial('my-project-team/my-project-navigation.phtml',array("step" => $this->sub_step,"project" => $this->project));
?>

<h3>Applications for LEVEL 1</h3>
<hr>
  	<div id="alert-area"></div>
    <!-- Add data-toggle="buttons-checkbox" for checkbox style toggling on btn-group -->
    	 <div id="model_list">
    		<script id="model_list_template" type="text/x-handlebars-template">
			
			<table class="table table-striped">
        	<thead>
    		<tr>
    			<th>ID</th>
				<th>Level</th>
    			<th>Date of application</th>
				<th>Member</th>
    			<th>Role</th>	
    			<th>Actions</th>
    		</tr>
    				</thead>
   				 <tbody>
				{{#each this}}				
				<tr>
						<td>{{id}}</td>
						<td>{{level}}</td>  
						<td>{{created}}</td>
						<td><a href="/member/profile/index/id/{{user_id}}">{{user_name}}</a></td>

						<td>{{role_name}}</td>  
						<td class="actions" id="{{id}}">
							<a class="btn btn-info" data-toggle="modal" href="#surveyModal-id-{{id}}" >Survey</a>
							<input  class="btn btn-success accept" type="submit"  data-loading-text="processing..." value="Accept" name="submit" />
							<input  class="btn btn-success deny" type="submit"  data-loading-text="processing..." value="Deny" name="submit" />
						</td>
				</tr>
				<!-- modal  -->
		    	<div class="modal hide" id="surveyModal-id-{{id}}">
				<div class="modal-body">
    			<p>{{{content}}}</p>
    			</div>
    				<div class="modal-footer"> <a href="#" class="btn" data-dismiss="modal">Close</a></div>
    			</div>
				
				{{/each}}
		    		 		
   			 </tbody>
    		</table>	
		</script>
		
</div>

<!-- modal deny form  -->
	<div class="modal hide" id="modal-form-deny">
	<form id="form-deny" enctype="application/x-www-form-urlencoded" class=" form-horizontal" action="/member/my-project-team/ajax-request/id/<?php echo $this->project->id;?>/_method/deny" method="post">

		<div class="modal-header"><button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Please Explain the reason why you have denied the member.</h3></div>
				<div class="modal-body">
			<fieldset id="fieldset-application_group">
				<input type="hidden" name="application_id" value="" class="" id="application_id">              
				<div class="control-group">
				
				<label for="message" class="control-label required">Reason</label>	
					<div class="controls">
						 <textarea name="message" id="message" rows="4" class="" cols="80"></textarea>
					</div>
				</div>
			</fieldset>
</div>
<div class="modal-footer">	
                    
<input type="submit" name="submit" id="submit" value="Confirm deny" class="btn btn-primary">
<button name="reset" id="reset" type="reset" value="
Reset" class="btn btn-primary">
Reset</button>
 <a href="#" class="btn" data-dismiss="modal">Close</a>
        		 </div>
       </form>	
    </div>
   
	
	
<script src="/media/tools/handlebars-1.0.0.beta.6.js"></script>   
        <script type="text/javascript">  

        // validation of deny-form	
       	var formDeny = $('#form-deny'); 
        formDeny.validate({
    	    		rules: {
    	    			message :{
    		    			required: true,
    	    				minlength: 2
    			    		}
    	    		},
    	    		   submitHandler: function(form) {
    	    			   formDeny.submit();				 		    
    			 		   }
    	    	}
    	   );	

			var Models = {
					
			init: function(config){
				// ajax setup
				$.ajaxSetup({
					url: "/member/my-project-team/ajax-request/id/<?php echo $this->project->id;?>", 
					type: 'POST',
					dataType: 'json',

				});
		
				this.config = config;
				this.bindEvents();
				this.setutTemplates();
				this.findData(); // fill the question_list
				},
			// setting template system
			setutTemplates: function(){
				this.config.modelListTemplate = Handlebars.compile(this.config.modelListTemplate);
					
				},
				
			bindEvents: function(){
				this.config.modelList.on('click','td.actions input.survey',this.findSurvey); // edit question 				
				this.config.modelList.on('click','td.actions input.accept',this.acceptMember); // edit question 	
				this.config.modelList.on('click','td.actions input.deny',this.showModaldenyMember); // edit question 			
				
				},
				
			findData: function(){
				 var self = Models;
					
				 $.ajax({
				 	data: "_method=findAllNewApplications",// take data from the form and send it to the method delete
					 }).done(
						function (results){
				 			self.config.modelList.empty();
							if(results.data[0]){
								self.config.modelList.append(self.config.modelListTemplate(results.data));
								//newAlert (results.respond, results.message)
							}else{
								self.config.modelList.append("No requests.");
							}
				 		}
				 );	
	
				},

			// find survey
			findSurvey:function(e){
				var self = Models;
				var par = $(this).parent();
				var application_id = par.attr("id");
				
				$(this).button('loading');
				console.log($(this));
				//delete method
				$.ajax({
					data:   "&_method=getSurvey&&application_id="+application_id, // take data from the form and send it to the method update
				}).done(
						function (results){
							newAlert (results.respond, results.message); // display alert
							self.findData(); // refresh questions
						}
				);
				e.preventDefault();
			},	
			
			// acceptMember
			acceptMember:function(e){
				var self = Models;
				var par = $(this).parent();
				var application_id = par.attr("id");
				$(this).button('loading');
				console.log($(this));
				$.ajax({
					data:   "&_method=accept&&application_id="+application_id, // take data from the form and send it to the method update
				}).done(
						function (results){
							newAlert (results.respond, results.message); // display alert
							self.findData(); // refresh questions
						}
				);
				e.preventDefault();
			},
			
			// prepare modal form for deny user
			showModaldenyMember:function(e){
				$('#modal-form-deny').modal('show');
				$('#form-deny #application_id').val($(this).parent().attr("id")); // add id
				e.preventDefault();
			},

			};

			Models.init({
				modelListTemplate: $('#model_list_template').html(),
				modelList: $("#model_list"),
			});
 </script>  

    
    
    <script>
 $(document).ready(function() {
      $("#searchInput").keyup(function(){
 		//hide all the rows
          $("#fbody").find("tr").hide();
 			//split the current value of searchInput
          var data = this.value.split(" ");
 			//create a jquery object of the rows
          var jo = $("#fbody").find("tr");
 			//Recursively filter the jquery object to get results. 
          $.each(data, function(i, v){
              jo = jo.filter("*:contains('"+v+"')");
          });
 			//show the rows that match.
          jo.show();
 			//Removes the placeholder text 
      }).focus(function(){
          this.value="";
          $(this).css({"color":"black"});
          $(this).unbind('focus');
      }).css({"color":"#C0C0C0"});
  });
</script>
</head>
<body>
 <input id="searchInput" value="Type To Filter"><br/>
 <table>
  <thead>
    <tr><th>Column1</th><th>Column2</th></tr>
  </thead>
  <tbody id="fbody">
    <tr><td>cat</td><td>one</td></tr>
    <tr><td>dog</td><td>two</td></tr>
    <tr><td>cat</td><td>three</td></tr>
    <tr><td>moose</td><td>four</td></tr>
    <tr><td>mouse</td><td>five</td></tr>
    <tr><td>dog</td><td>six</td></tr>
  </tbody>
 </table>
</body>
</html>
    
    
    
    
