<?php 
// The main project navigation
$this->step = 6;
echo $this->partial('my-project/my-project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

<?php 
// The main project navigation
$this->sub_step = 2;
echo $this->partial('my-project-team/my-project-navigation.phtml',array("step" => $this->sub_step,"project" => $this->project));
?>

<h3>Members waiting for response <span class="badge badge-info"><?php echo $this->paginator->getTotalItemCount(); ?></span></h3>

<hr />

<!-- Updates Table -->
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    <?php if (count($this->paginator)) {?>
 
        <table class="table table-striped">
        <thead>
    		<tr>
    			<th>Level</th>
    			<th>Date of application</th>
    			<th>Role</th>
    			<th>Description</th>		
    			<th>Actions</th>
    		</tr>
    	</thead>
    <tbody>
    <?php foreach ($this->paginator as $application){ ?>
    	<tr>
    	<td><?php echo $application->level; ?></td>
		<td><?php echo $application->created->format('Y/m/d'); ?></td>	
		<td><?php echo $application->roleName; ?></td>		
		
		<td><?php echo $application->modified->format('Y/m/d'); ?></td>		
    	<td> 
    		<a class="btn btn-info" href="/member/my-project/update-edit/id/<?php echo $this->project->id?>/update_id/<?php echo $application->id ?>">Edit</a> ~
    		<a class="btn btn-warning" href="/member/my-project/update-delete/id/<?php echo $this->project->id?>/update_id/<?php echo $application->id ?>">Delete</a>
 
    	</td>			
    	</tr>	 		
    <?php } ?>
    </tbody>
    </table>
    	
    		
    <?php }?>

