<?php echo '<?xml version="1.0" encoding="utf-8"?>'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
 <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
  <link rel="shortcut icon" href="/css/default/favicon.ico" />
 <link rel="stylesheet" type="text/css" href="/css/default/style_launchpage.css"/
<link href="https://plus.google.com/b/112825861114326373315/" rel="publisher" />
  <title>FLO~ Start.Build.Lead.Grow.</title>
 </head>
 <body>
 
 <div id="box">
    <h1><span>FLO~ Start.Build.Lead.Grow.</span></h1>
    
    <div id="right">
    <img src="/css/default/platform.png" alt="platform" id="platform" />
    
    <?php echo $this->layout()->content; ?>
    
     <div id="icons">
       <a href="http://www.facebook.com/floplatform" title="FLO~ on Facebook" onclick="window.open(this.href); return false;"><img src="/css/default/icon_fb.png" alt="facebook" /></a>
       <a href="https://twitter.com/#!/flo_platform" title="FLO~ on Twitter" onclick="window.open(this.href); return false;"><img src="/css/default/icon_twitter.png" alt="twitter" /></a>
       <a href="http://floplatform.tumblr.com/" title="FLO~ on Tumblr" onclick="window.open(this.href); return false;"><img src="/css/default/icon_tumblr.png" alt="tumblr" /></a>
       <a href="http://vimeo.com/floplatform" title="FLO~ on Vimeo" onclick="window.open(this.href); return false;"><img src="/css/default/icon_vimeo.png" alt="vimeo" /></a>
    </div>
    
    <div id="social">
      <g:plusone size='small' count='true' href='http://www.floplatform.com'></g:plusone>
      <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.floplatform.com&amp;send=false&amp;layout=button_count&amp;width=160&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:160px; height:21px;" allowTransparency="true"></iframe>  
   
    <!-- Place this tag where you want the badge to render-->
    <a href="https://plus.google.com/b/112825861114326373315/?prsrc=3" style="text-decoration: none; color: #333;"><div style="display: inline-block; *display: inline;"><div style="text-align: center;"><img src="https://ssl.gstatic.com/images/icons/gplus-32.png" width="32" height="32" style="border: 0;"></img></div></div></a>

    </div>
    
    </div>
 
 </div>
     

    


 </body>
</html>
