<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  	<title>Project-F Beta / Project / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <link rel="stylesheet" href="<?=$this->baseUrl('/media/data-tables-1.9.1/css/data-table-bootstrap2-additional.css')?>">
  <?= $this->action('lib', 'index', 'site');  // libraries ?>
 </head>
<body>
 		<?= $this->action('header', 'index', 'site');  ?>
 			<?php 
		// if the user has identity
    	if(Zend_Auth::getInstance()->hasIdentity()){
    		echo $this->action('admin-menu', 'index', 'admin');  
    	}	
    	
   
    	
  	  ?>
  	 <hr>		 
	 <?= $this->action('menu-debug', 'menu', 'project');  ?>  
	  	
	 <?php // creator menu
    	if($this->isCreator){
    		echo $this->action('menu-creator', 'menu', 'project',array("id" => $this->project->id));
    	}
    	// collaborator widget
    	if($this->isCollaborator){
    		echo "Yes, you are collaborating in this project.";
    		echo "<hr>";
    	}
     ?>
    <hr>
	<?= $this->action('breadcrumbs', 'index', 'site');  ?>
	 <hr>
	<div class="row" style="margin-left: 10px"> 
	      <div class="span6">
	      	<!-- Bootstrap messaging generator -->
	      	<?php echo $this->flashMessenger() ; ?>
	        <?php echo $this->layout()->content; ?>
	      </div>
	    
	    <div class="span6">
	    	<h3>Widgets</h3>
			<!-- Levels and Tasks module -->
	        <?= $this->action('task', 'widget', 'project',array("id" => $this->project->id));  ?>
	    	
	    
	    	<!-- Form Application -->
	        <?= $this->action('application', 'widget', 'project',array("id" => $this->project->id));?>
	    	<!-- Similar projects -->
	     </div>
  
    </div>
    
    <footer>
      <?= $this->action('footer', 'index', 'site');  ?>
    </footer>

</body>
</html>