<!DOCTYPE HTML>

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Project-F Beta / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="<?=$this->baseUrl('/media/data-tables-1.9.1/css/data-table-bootstrap2-additional.css')?>">
    <?= $this->action('lib', 'index', 'site');  // libraries ?>
    <link rel="stylesheet" href="<?=$this->baseUrl('/media/slepice-site/1.0.0/css/flow_css.css')?>">

</head>

<body>
 	<div id="fl-container">
   <div class="container">
     <?= $this->action('header', 'index', 'site');  ?>
   </div>

 			<?php 
		// if the user has identity
    	if(!Zend_Auth::getInstance()->hasIdentity()){
    		echo $this->action('admin-menu', 'index', 'admin');  
    	}	
    	
   
    	
  	  ?>
	 
	 <?= $this->action('menu-debug', 'menu', 'project');  ?>  
	  	
	 <?php // creator menu
    	if($this->isCreator){
    		echo $this->action('menu-creator', 'menu', 'project',array("id" => $this->project->id));
    	}
    	// collaborator widget
    	if($this->isCollaborator){
    		echo "Yes, you are collaborating in this project.";
    		echo "<hr>";
    	}
     ?>
  <div id="fl-content">
   <div class="container"> 
	<?= $this->action('breadcrumbs', 'index', 'site');  ?>
	 

        <div class="row">
          <div class="span11">
 	<!-- Bootstrap messaging generator -->
 	<?php echo $this->flashMessenger() ; ?>
  <?php echo $this->layout()->content; ?>
  	    
	        <div class="span4 fl-sidebar">
	    	    <div class="inner">
                <!-- Levels and Tasks module -->
                <h3 class="fl-sidebar-h3-first">Project Level</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-project-level">
                  <div class="progress">
                    <div class="fl_level<?php echo $this->project->level;?>"></div>
                  </div>
                  <p class="fl-project-level-info"><a href="" title="Learn more about Levels">Learn more about Levels</a></p>
                </div>

                <?php
	//                echo $this->action('task', 'widget', 'project',array("id" => $this->project->id));  ?>
	    	      
                <h3 class="fl-sidebar">Team</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-team">
                  <div class="fl-team-author">
                    <div class="fl-team-author-roles">
                      <img src="slepice/img/role40x40_3.png" alt="" title="" />
                      <img src="slepice/img/role40x40_4.png" alt="" title="" />
                    </div>
                    <div class="fl-team-author-created">
                      <span>Project created by</span>
                      <span class="fl-team-author-name">Name of the author</span>
                    </div>
                  </div>

                  <div class="fl_thin_divider"></div>
                  
                  <div class="fl-team-join-team">
                    <div class="inner">
                      <!-- Form Applications for Level 1 -->
                      <?php 
                        if($this->project->level == 1)          
                             echo $this->action('application', 'widget', 'project',array("id" => $this->project->id));?>
                          <!-- Form Applications for Level 2 -->
                       <? if($this->project->level == 2)
                            echo $this->action('application-level2', 'widget', 'project',array("id" => $this->project->id));?>
                     </div>
                  </div>
                </div>


                <h3 class="fl-sidebar">Passion Slider</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-passion-slider">
                <div class="progress fl-passion-bar">
                  <div class="bar fl-bar" style="width: 60%;"></div>
                </div>
                </div>
				
				<!-- Polls widget -->
   				<?php echo $this->action('poll', 'widget', 'project',array("id" => $this->project->id));?>
                
				<!-- Similar projects widget -->
				<?php echo $this->action('similar', 'widget', 'project',array("id" => $this->project->id));?>
             

	         </div>
         </div>
         
       </div>
     </div>
   </div>
 </div>
  
 <div class="fl-bottom-line">
      <?= $this->action('footer', 'index', 'site');  ?>
 </div>

</body>
</html>