<?php 
echo $this->partial('project/create-project-navigation.phtml',array("step" => $this->step));
?>
<div id="alert-area"></div>
<h2>SURVEY PAGE</h2>

    <form class="form-horizontal" id="step">
    <fieldset title="Step 1">
   		 <legend>First Q</legend>
    		<div class="control-group">
    
    			<label class="control-label" for="input01">Text input</label>
   			 <div class="controls">
   			 <input type="text" class="input-xlarge" id="input01">
    		<p class="help-block">Supporting help text</p>
    		</div>
    
    		</div>
    </fieldset>
    
    <fieldset title="Step 2">
   		 <legend>First 2</legend>
    		<div class="control-group">
    
    	<label class="control-label" for="input01">Text input</label>
   			 <div class="controls">
   			 <input type="text" class="input-xlarge" id="input01">
    		<p class="help-block">Supporting help text</p>
    		</div>
    
    		</div>
    </fieldset>
    
    
    		<input type="submit" class="finish"/>
    
    </form>
    
 

<?php // echo $this->form;   ?>


<!-- Load jQuery build -->
<script type="text/javascript" src="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/js/jquery.validate.min.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/js/jquery.stepy.js')?>"></script>
<script type="text/javascript">
$(document).ready(function()
		{	// disable cache
			 $.ajaxSetup ({cache: false });  

			 $('#step').stepy({
				  description:  false,
				  legend:       true,
				  titleClick:   true,
				  titleTarget:   'empty'
				  
				});		

		
			 
				    

});



</script>