<?php 
echo $this->partial('project/create-project-navigation.phtml',array("step" => $this->step));

?>
 <div class="alert alert-info">
 <span class="label label-info">Info</span>
 	Image will be automatically cropped. Try to upload image which has resolution 480x320 to have the best image quality and proportion.
</div>


<div id="alert-area"></div>


<form id="imageform" enctype="multipart/form-data" class="form-horizontal well" action="/member/ajax/create-thumbnail" method="post">
<fieldset id="fieldset-CreateProjectChooseProfilePhoto">
  <legend>Step 2 / Choose Picture</legend>
  <div id="preview">
  <?php 
	// display picture from the previous
	if(Zend_Session::namespaceIsset('projectStep2')){
		$session = Zend_Session::namespaceGet('projectStep2');
		if(isset($session['secondFormData'])){
			echo '<div class="well"> <img src="'.$session['secondFormData']['webUrl'].'?foo='.time().'" alt="Profile Picture"/> </div> <hr />';
		}	
	}
  ?>
  </div> 
 <div class="control-group">
  <label for="project_picture" class="control-label optional">Choose Picture</label>
 <div class="controls">
<input type="file" name="photoimg" id="photoimg" class="input-file">
<p class="help-block">Max size 4MB (jpg,jpeg,png)</p></div>
</div>
</fieldset>
<div class="form-actions">

<a class="btn btn-large btn-primary" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-one'),null,true)?>">Previous</a>
<a class="btn btn-large btn-primary" id="button-continue" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-three'),null,true)?>">Next</a>
</div>
</form>




<?php // echo $this->form;   ?>


<!-- Load jQuery build -->
<script type="text/javascript" src="<?=$this->baseUrl('/media/tools/jquery.form.js')?>"></script>

<script type="text/javascript">
$(document).ready(function()
{
	// disable cache
	 $.ajaxSetup ({cache: false });  
	 <?php 
	  // display picture from the previous
	  if(!Zend_Session::namespaceIsset('projectStep2')){
	  echo '$("#button-continue").hide();';}
	  ?>
	  
	   var options = { 
		        target: '#preview',   // target element(s) to be updated with server response 
		        success: showResponse,  // post-submit callback 
		        error: showError,  // post-submit callback 
		        dataType: 'json'        // 'xml', 'script', or 'json' (expected server response type) 
	  }; 

		$('#photoimg').live('change', function()
		{
			$("#preview").html('');
			$("#preview").html('<img src="/img/loader.gif" alt="Processing picture..."/>');
			$("#imageform").ajaxForm(options).submit();
		});
 
		// post-submit callback 
		function showResponse(responseText, statusText, xhr, $form)  { 
			if(responseText.error){
				newAlert('error', "Please check if you are uploading image and size is lower than 4MB.");
				$("#preview").html('');
			}else{
				$("#preview").html('');
				$("#preview").html('<div class="well"> <img src="'+responseText.web_url+'?foo=' + new Date().getTime()+'" alt="Profile Picture"/> </div> <hr />');
				$("#button-continue").show();
				newAlert('success', responseText.success);
			} 
		} 
		
		// post-submit callback 
		function showError(responseText, statusText, xhr, $form)  { 
		    alert('status: ' + statusText + '\n\nresponseText: \n' + xhr.toSource() + 
		        'We are sorry, but something is wrong. Try to check if your image is allright.'); 
		} 		
});
</script>
