<!doctype html>
<head>
  <meta charset="utf-8">
  <title>Project-F Beta / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <?= $this->action('lib', 'index', 'site');  // libraries ?>
</head>

<body>
 <div class="row-fluid" style="margin-left:10px">
  <div class="span11" >
   
   <?= $this->action('header', 'index', 'site');  ?>
     
   <?php 
		// if the user has identity
    	if(Zend_Auth::getInstance()->hasIdentity()){
    		echo $this->action('member-menu', 'dashboard', 'member');  
    	}
   ?>
   
   <?= $this->action('breadcrumbs', 'index', 'site');  ?>
   
    <div class="row-fluid"> 
       <div class="span2" >
      	   <?= $this->action('left-menu', 'index', 'site');  ?>
      </div>
      <div class="span10">
      	<!-- Bootstrap messaging generator -->
      	<?php echo $this->flashMessenger() ; ?>
        <?php echo $this->layout()->content; ?>
      </div>
    </div>
    
    <footer>
      <?= $this->action('footer', 'index', 'site');  ?>
    </footer>
  </div>
</div>


</body>
</html>