<!doctype html>
<head>
  <meta charset="utf-8">
  <title>Project-F Beta / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <link rel="stylesheet" href="<?=$this->baseUrl('/css/style.css')?>">
  <link rel="stylesheet" href="<?=$this->baseUrl('/media/bootstrap/css/bootstrap.css')?>">
    <link rel="stylesheet" href="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/css/jquery.stepy.css')?>">
   <script src="<?=$this->baseUrl('js/libs/modernizr-2.0.6.min.js')?>"></script>
    <script src="<?=$this->baseUrl('media/tools/jquery-1.7.1.min.js')?>"></script>
</head>

<body>
 <div class="row-fluid" style="margin-left:10px">
  <div class="span11" >
   
   <?= $this->action('header', 'index', 'site');  ?>
     
   <?php 
		// if the user has identity
    	if(Zend_Auth::getInstance()->hasIdentity()){
    		echo $this->action('member-menu', 'dashboard', 'member');  
    	}
   ?>
   
   <?= $this->action('breadcrumbs', 'index', 'site');  ?>
   
    <div class="row-fluid"> 
       <div class="span2" >
      	   <?= $this->action('left-menu', 'index', 'site');  ?>
      </div>
      <div class="span10">
      	<!-- Bootstrap messaging generator -->
      	<?php echo $this->flashMessenger() ; ?>
        <?php echo $this->layout()->content; ?>
      </div>
    </div>
    
    <footer>
      <?= $this->action('footer', 'index', 'site');  ?>
    </footer>
  </div>
</div>
  <!-- scripts concatenated and minified via ant build script-->

  <script defer src="<?=$this->baseUrl('media/bootstrap/js/bootstrap.js')?>"></script>
  <!-- end scripts-->

</body>
</html>