<!-- Carousel Slideshow Module -->
<div id="myCarousel" class="carousel">
  <div class="carousel-inner">
   <?php 
    $active = true;
   	for($i=1;$i<6;$i++){
   		$project = $this->slideshow->getProject($i);
   		if($project){ ?>
		<div class="item <?php if($active == true) {echo "active";$active = false;} // first project is set to be active?>">   		
   			<p><img alt="<?php echo $project->title; ?> - main picture" src="/storage/projects/<?php echo $project->dir."/".$project->getPicture('small'); ?> " /></p>	
   			<?php echo $project->title; ?>
		</div>	
   	<?php
   		}
   }
   ?>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
